### ISSUE TITLE
运行不起来啊？

### ISSUE THREAD

**Issue by 627443839** [yezihaohao/NeteaseCloudMusic#2]
环境
node v8.6.0
xcode 9

报如下错误

ld: library not found for -lRNBlur
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld build/Build/Products/Debug-iphonesimulator/NeteaseCloudMusic.app/NeteaseCloudMusic normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NeteaseCloudMusic.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NeteaseCloudMusic.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by yezihaohao** [comment]
没遇到过这个问题呢。用sudo 运行试试或者看下8081的端口是否占用。
这里有很多方案，你可以参考下：
https://github.com/facebook/react-native/issues/14423
https://github.com/facebook/react-native/issues/10401

**Comment by yezihaohao** [comment]
https://github.com/facebook/react-native/issues/7308

**Comment by selectersky** [comment]
我也有这个问题，感觉是少了RNBlur这个依赖库

**Comment by selectersky** [comment]
在目录运行如下命令：

```sh
$ npm install react-native-blur 
```
问题解决。
