### ISSUE TITLE
Genymotion 虚拟机跑起来网络有问题

### ISSUE THREAD

**Issue by setsuna** [yezihaohao/NeteaseCloudMusic#3]
Network request failed

**Comment by yezihaohao** [comment]
网络什么问题？运行了那个api项目？

**Comment by zhuyu666** [comment]
我也同样的环境遇到这样的问题，启动就会出现

启动程序后模拟器上持续loading,错误提示：
Possbile Unhandled Promise Rejection(id:1)
typeError: request failed
......

API已在本地node启动
云音乐基础IP设置的127.0.0.1:3000

恳请大家帮助~~

**Comment by zhuyu666** [comment]
替换IP 本地是要替换成127.0.0.1吗

**Comment by yezihaohao** [comment]
@zhuyu666  把127.0.0.1替换成本机的ip地址，192.x.x.x

**Comment by zhuyu666** [comment]
@yezihaohao 非常感谢，问题迎刃而解，程序运行中会出现一些黄色警告，不过不影响使用，万分感谢谢！！

**Comment by zhanfangzxc** [comment]
@zhuyu666 
![image](https://user-images.githubusercontent.com/6426836/32650173-64507280-c5c2-11e7-8b28-ed654bffb4aa.png)
请问你是改了这个地址吗，这个就是我改成自己电脑的ip地址，可是还是不行，还是会报网络请求失败的错误
