### ISSUE TITLE
react-native run-android 报错

### ISSUE THREAD

**Issue by selectersky** [yezihaohao/NeteaseCloudMusic#4]
Scanning 599 folders for symlinks in /d/source/rn/NeteaseCloudMusic/node_modules (6ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

1. Genymotion 4.2.2 API 17，已经运行
2. 使用react-native init Test，然后run-android，能在Genymotion里面正常运行

issue:是否必须要5.1 API 22  才可以？还是有其它问题？

**Comment by yezihaohao** [comment]
建议安卓版本6.0运行。4.x的版本没试过，可能个别插件库有问题

**Comment by selectersky** [comment]
问题原因：android/gradlew没有执行权限
解决方法，在工程目录，执行如下命令：

```sh
$ chmod +x android/gradlew
```

>>这么简单的问题，贴出来，希望大家引以为戒，@yezhihaohao，可以在帮助文档里面说明下。Mac电脑，这个问题肯定会出现。
