### ISSUE TITLE
react-native run-ios以后报错

### ISSUE THREAD

**Issue by YangZhenFang** [yezihaohao/NeteaseCloudMusic#5]
![react-native](https://user-images.githubusercontent.com/13129167/32593121-a75b4174-c561-11e7-9917-7c04ab9b3015.jpg)
想咨询一下是什么原因？谢谢

**Comment by yezihaohao** [comment]
运行环境以及运行步骤是什么？npm或yarn建议都配置 淘宝镜像源。具体操作react native 中文网有

**Comment by elonglau** [comment]
同是这个问题，一直编译失败。是不是你用的RN版本太高了，装了别的编译工具？

**Comment by yezihaohao** [comment]
@elonglau  可能是这个原因。因为我用了科学上网工具，所以没出现过这个问题。
[https://github.com/facebook/react-native/issues/15964](https://github.com/facebook/react-native/issues/15964)
[https://github.com/facebook/react-native/issues/7308](https://github.com/facebook/react-native/issues/7308)

中文网有个解决方案。可以试一下（或者建议打开科学上网工具）
[http://reactnative.cn/blog.html](http://reactnative.cn/blog.html)
[http://bbs.reactnative.cn/topic/4301/ios-rn-0-45以上版本所需的第三方编译库-boost等](http://bbs.reactnative.cn/topic/4301/ios-rn-0-45以上版本所需的第三方编译库-boost等)

**Comment by yezihaohao** [comment]
[https://github.com/facebook/react-native/issues/14423](https://github.com/facebook/react-native/issues/14423)

**Comment by luocheng2013** [comment]
我编译也是遇到上面的问题，用终端run-ios包那个错，用xcode跑，其实是依赖的三个.a包找不到。

**Comment by yezihaohao** [comment]
@luocheng2013  确实如此。我检查了下，有个废弃包在iOS端依赖没有移除干净。更新了，再拉代码试试
