### ISSUE TITLE
TypeError: Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by yy9306** [yezihaohao/NeteaseCloudMusic#9]
安装`react-native-video`， 运行的时候有没有遇到 `TypeError: Cannot read property 'Constants' of undefined` 这个问题， 谢谢了

**Comment by yezihaohao** [comment]
没遇到过呢。运行react-native link 了吗或者重新打包编译试试。可以在issues里面找找方案[https://github.com/react-native-community/react-native-video/issues/438](https://github.com/react-native-community/react-native-video/issues/438)

**Comment by yy9306** [comment]
嗯嗯， 谢谢了， 这些我看过了， 我在找找其它方案吧
